### ISSUE TITLE
if video has uploader-added-subtitle, subtitle extractor will fail

### ISSUE THREAD

**Issue by kjy00302** [kjy00302/youtube-dl#1]
```
$ youtube-dl http://tvple.com/208230 --write-sub
[tvple] 208230: Downloading webpage
[tvple] playurl_208230: Downloading webpage
[tvple] clouds_xml: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tvple.py", line 96, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1318, in extract_subtitles
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tvple.py", line 67, in _get_subtitles
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tvple.py", line 59, in _convert_sub
AttributeError: 'NoneType' object has no attribute 'group'
```
```
$ youtube-dl http://tvple.com/208230
[tvple] 208230: Downloading webpage
[tvple] playurl_208230: Downloading webpage
[download] Destination: 소환사 협곡의 개새끼-208230.mp4
[download] 100% of 6.74MiB in 00:00
```

**Comment by kjy00302** [comment]
sample cloud xml file
[newcloud.txt](https://github.com/kjy00302/youtube-dl/files/47527/newcloud.txt)

**Comment by kjy00302** [comment]
fixed!
f4a7e38
